name: Release a CV

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  call_rendercv_workflow:
    name: RenderCV
    uses: ./.github/workflows/rendercv.yaml

  build:
    needs: call_rendercv_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download RenderCV Output
        uses: actions/download-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - name: Move PDFs
        run: mv rendercv_output/*.pdf dist
        shell: bash
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          deploy_key: ${{ secrets.PAGES_SECRET }}
          publish_dir: dist
          allow_empty_commit: true
          force_orphan: true
          enable_jekyll: true
